---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - aws.stilll.fr
  resources:
  - certificatesyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.stilll.fr
  resources:
  - certificatesyncs/finalizers
  verbs:
  - update
- apiGroups:
  - aws.stilll.fr
  resources:
  - certificatesyncs/status
  verbs:
  - get
  - patch
  - update
